### PR TITLE
FIX: modal should close on esc and overlay click

### LINKED ISSUE #184: FIX: modal should close on esc and overlay click

### PR DESCRIPTION
**Pull request by Kannolas**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #184 

## QA Instructions, Screenshots, Recordings
  
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._

### CODE REVIEW

File: src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -56,11 +59,17 @@ export const ModalHeader = ({ size = 'm', children, className, ...rest }: ModalH
     return <div className={cn(s.Header, sizeMap[size], className, { ...rest })}>{children}</div>;
 };
 
-export const Modal = ({ size = 'm', isOpen, onClose, children, className, ...props }: ModalProps) => {
+export const Modal = ({ size = 'm', isOpen, onClose, children, className, overlayClose, ...props }: ModalProps) => {
     const [onESC] = useKeyboard([KeyCode.Escape], () => onClose?.(), {
```
Comment (DenisVorop) [inline src/components/Modal/Modal.tsx:63]: () => onClose() -> onClose

**Review by DenisVorop — CHANGES_REQUESTED** [review]

**Review by DenisVorop — APPROVED** [review]
