### PR TITLE
FIX: pagination component

### LINKED ISSUE #206: FIX: pagination component

### PR DESCRIPTION
**Pull request by maxim-dolgovmd**
## PR includes

- [X] Bug Fix

## Related issues

Resolve #206

### CODE REVIEW

File: src/components/Pagination/Pagination.tsx [hunk 1]
```diff
@@ -9,7 +9,7 @@ import s from './Pagination.module.css';
 function LeftIcon() {
     return (
         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
-            <path d="M12.8 1.06667L5.33334 8L12.8 14.9333" stroke="#554AE2" strokeLinecap="square" />
```
Comment (DenisVorop) [inline src/components/Pagination/Pagination.tsx:12]: icons should be from icons lib

File: src/components/Pagination/Pagination.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ function LeftIcon() {
 function RightIcon() {
     return (
         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
-            <path d="M5.33331 14.9333L12.8 8L5.33331 1.06667" stroke="#554AE2" strokeLinecap="square" />
+            <path d="M5.33331 14.9333L12.8 8L5.33331 1.06667" stroke="var(--icons-brand)" strokeLinecap="square" />
```
Comment (DenisVorop) [inline src/components/Pagination/Pagination.tsx:21]: icons should be from icons lib

**Review by DenisVorop — CHANGES_REQUESTED** [review]

**Review by DenisVorop — APPROVED** [review]
